load loads
mod TEST is
    pr SEMANTICS .  
    
    op list : -> ListType .
    eq list = int(4), int(2) ,int(3) .
endm
--- red list .
--- red eval(['a, (intType 5)], int(6)) .
--- red numCallArgument([]) .
--- red numCallArgument([emptyExpressionList]) .
--- red numCallArgument(['q,, int(8)]) .
--- red numCallArgument([int(4),, int(5),, int(9)]) .
--- red modifyElementList(list,string("nuevo"), 0, 0) .
--- rew { none | ('a = list(int(3) int(2) int(4))); ('size = size('a)); } .

--- red numArgumentList(()) .
--- red numArgumentList((emptyQidList)) .
--- red numArgumentList(('a)) .
--- red numArgumentList(('a 'b 'c)) .

q